# Generated by Django 4.2.4 on 2023-08-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='like',
        ),
    ]
