# Generated by Django 4.2.4 on 2023-08-13 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='store/images'),
        ),
    ]
